## Numpy

Импортировать NumPy под именем np

In [ ]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
vector0 = np.zeros(10)
vector0


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [5]:
vector1 = np.ones(10)
vector1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
vector_2 = np.full(10, 2.5)
vector_2

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
vector_3 = np.zeros(10)
vector_3[4] = 1
vector_3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [14]:
vector_direct = np.linspace(2.0, 20.0,num = 10) # числа - по возрастанию
vector_4 = vector_direct[::-1]
vector_4 # теперь числа - в убывающем порядке

array([20., 18., 16., 14., 12., 10.,  8.,  6.,  4.,  2.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [20]:
array_2d = np.arange(0,9).reshape(3,3) # форма 2*2, но это все еще array
matrix_1 = np.asmatrix(array_2d) # преобразуем к matrix
matrix_1

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [37]:
# решение 1
source = [1,2,0,0,4,0]
non_zeros = []

for i in range(0, len(source)):
    if source[i] != 0:
        non_zeros.append(i)

non_zeros

[0, 1, 4]

In [47]:
# решение 2
source = [1,2,0,0,4,0]
non_zeros = []

for index,value in enumerate(source):
    if(value != 0):
        non_zeros.append(index)

non_zeros

[0, 1, 4]

In [41]:
# решение 3
source = [1,2,0,0,4,0]
non_zeros = np.nonzero(source)

non_zeros

(array([0, 1, 4], dtype=int64),)

Создать 3x3 единичную матрицу

In [39]:
matrix_ones = np.asmatrix( np.ones(3*3).reshape(3,3) )

matrix_ones

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [78]:
# решение 1
def random_value(x,y,z):
    return np.random.rand(1)[0]
    
array_random_3 = np.fromfunction(np.vectorize(random_value), (3, 3, 3))
array_random_3

[0.82590074]
[0.40134124]


array([[[0.45714734, 0.31744591, 0.09699604],
        [0.01453289, 0.8018202 , 0.43983982],
        [0.73254752, 0.51864508, 0.9405144 ]],

       [[0.63983969, 0.81212913, 0.92779915],
        [0.22331962, 0.35459023, 0.51084455],
        [0.03848142, 0.68539542, 0.30760744]],

       [[0.65783016, 0.18151783, 0.68333247],
        [0.01452393, 0.29642495, 0.73641481],
        [0.4572264 , 0.11941392, 0.01804086]]])

In [87]:
# решение 2
array_random_3 = np.random.rand(3,3,3) # то же самое: np.random.random((3,3,3))
array_random_3

array([[[0.56701064, 0.11758192, 0.72547537],
        [0.57179396, 0.77919383, 0.81595503],
        [0.32559554, 0.44838298, 0.03584109]],

       [[0.93391142, 0.73635044, 0.05661089],
        [0.03054243, 0.2940222 , 0.27590153],
        [0.81388121, 0.24120031, 0.48123296]],

       [[0.04674435, 0.17912855, 0.69978576],
        [0.9092048 , 0.12023088, 0.23923819],
        [0.27174932, 0.76352118, 0.60028769]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [80]:
vect_30 = np.random.rand(30)
print(vect_30)
result_avg = np.average(vect_30) # np.mean(vect_30) - то же самое
result_avg

[0.36907259 0.07853174 0.88516651 0.67536158 0.71182558 0.36910057
 0.44242865 0.31031124 0.33136343 0.00417377 0.40464693 0.91031782
 0.59747706 0.99259786 0.67541495 0.39370386 0.58369885 0.1159068
 0.19239747 0.08119799 0.44909682 0.66801057 0.96417616 0.1939586
 0.04277139 0.96747722 0.64276153 0.00793909 0.29520511 0.04734472]


0.44678121582328173

Перемножить матрицы 5x3 и 3x2

In [88]:
matrix_1 = np.asmatrix(np.random.rand(5,3))
matrix_2 = np.asmatrix(np.random.rand(3,2))

result_matrix = matrix_1 * matrix_2 # как вариант:  np.dot(matrix_1, matrix_2)

result_matrix

matrix([[0.51161398, 0.30862579],
        [0.31609593, 0.17883594],
        [0.55957552, 0.36544031],
        [0.56461625, 0.96296012],
        [0.39414965, 0.49771203]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [98]:
result_vector = np.linspace(0,1,11, endpoint=False)[1:]
result_vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [102]:
source_vector = np.linspace(1,2,10, endpoint=False)
source_vector[3] = sum(source_vector) # сделаем так, чтобы max_value - было где-то в центре
source_vector[source_vector.argmax()] = 0
source_vector

array([1. , 1.1, 1.2, 0. , 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Преобразовать массив из float в int

In [122]:
source_array = np.arange(10, dtype=np.float32)
result_array = source_array.astype(np.int64, copy = False)

source_array, result_array

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [127]:
source_coords = np.random.random((10,2))

import scipy.spatial
distances = scipy.spatial.distance.cdist(source_coords, source_coords, metric='euclidean')
 
distances

array([[0.        , 0.21568763, 0.68487141, 0.65962807, 0.28062345,
        0.46447734, 0.20850309, 0.36735005, 0.12372906, 0.71281311],
       [0.21568763, 0.        , 0.57966873, 0.51430342, 0.2130399 ,
        0.34680502, 0.2895112 , 0.3486966 , 0.31643942, 0.67461188],
       [0.68487141, 0.57966873, 0.        , 0.14627501, 0.405328  ,
        0.87593113, 0.8525621 , 0.34421434, 0.68158046, 0.22686907],
       [0.65962807, 0.51430342, 0.14627501, 0.        , 0.38425809,
        0.77392202, 0.80095917, 0.37457974, 0.6828845 , 0.36860776],
       [0.28062345, 0.2130399 , 0.405328  , 0.38425809, 0.        ,
        0.55747417, 0.4523658 , 0.13733865, 0.30101608, 0.46582928],
       [0.46447734, 0.34680502, 0.87593113, 0.77392202, 0.55747417,
        0.        , 0.33681815, 0.69443091, 0.58819832, 1.00698748],
       [0.20850309, 0.2895112 , 0.8525621 , 0.80095917, 0.4523658 ,
        0.33681815, 0.        , 0.56208462, 0.31172448, 0.90859846],
       [0.36735005, 0.3486966 , 0.3442143

Случайно расположить p элементов в 2D массив

In [137]:
# условие
p = 5
n = 3
m = 3
elements = np.random.random(p) # элементы, которые располагать
result = np.zeros((n,m)) # массив, в который располагать элементы

np.put(result, np.random.choice(range(n*m), p, replace=False),  elements)
result

array([[0.08657815, 0.        , 0.        ],
       [0.2394966 , 0.48112871, 0.        ],
       [0.6240954 , 0.        , 0.70704748]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [139]:
source = np.array([1,2,3,4,5]) # исходный массив
zero_count = 3 # кол-во нулей, которые располагать между элементами
result = np.zeros(len(source) + (len(source)-1)*(zero_count)) # итоговый массив: создаем из нулей, и потом заменим нужные элементы из source
result[::zero_count+1] = source # каждый элемент, который выпадает не на 0 - подставляем из исходного масива

result

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

Найти наиболее частое значение в массиве

In [146]:
source = np.random.randint(low = 4, high = 9, size = 10) # числа: min = low, max = high - 1. Всего 10 чисел
occurances = np.bincount(source) # значение i-го элемента в массиве = кол-во раз, которое встречалось число i
print(occurances)
max_frequent = occurances.argmax() # в каком элементе массива наибольшее значение

max_frequent

[0 0 0 0 1 1 2 1 5]


8

Найти n наибольших значений в массиве

In [157]:
# решение = отсортировать по убыванию и взять первые n элементов
n = 5
source = np.random.randint(low = 1, high = 10, size = 15)
print(source)
sorted_array = np.flip(np.sort(source))
print(sorted_array)
result_array = sorted_array[:n]

result_array

[7 7 8 7 1 1 4 6 4 5 7 8 1 2 4]
[8 8 7 7 7 7 6 5 4 4 4 2 1 1 1]


array([8, 8, 7, 7, 7])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [159]:
import pandas as pd

In [227]:
# en_openfoodfacts_org_products.tsv
food = pd.read_csv('./en_openfoodfacts_org_products.tsv', delimiter='\t', encoding='utf-8', low_memory=False) # для загрузки нескольких строк - можно указать nrows=5
food.head()

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Посмотреть первые 5 записей

In [212]:
food[:5]

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [260]:
print(food.shape[0]) # вариант 1, наиболее понятный
print(food.iloc[:,5].count()) # вариант 2, но, тут нужно проверять, что нет пропусков - например, для первых столбцов результат отображает меньший
len(food.index) # вариант 3, наиболее быстрый по скорости выполнения: https://stackoverflow.com/questions/15943769/how-do-i-get-the-row-count-of-a-pandas-dataframe

356027
356027


356027

Сколько столбцов в наборе данных?

In [214]:
food.columns.size

163

Напечатайте все названия столбцов

In [215]:
print(food.columns.values)

['code' 'url' 'creator' 'created_t' 'created_datetime' 'last_modified_t'
 'last_modified_datetime' 'product_name' 'generic_name' 'quantity'
 'packaging' 'packaging_tags' 'brands' 'brands_tags' 'categories'
 'categories_tags' 'categories_en' 'origins' 'origins_tags'
 'manufacturing_places' 'manufacturing_places_tags' 'labels' 'labels_tags'
 'labels_en' 'emb_codes' 'emb_codes_tags' 'first_packaging_code_geo'
 'cities' 'cities_tags' 'purchase_places' 'stores' 'countries'
 'countries_tags' 'countries_en' 'ingredients_text' 'allergens'
 'allergens_en' 'traces' 'traces_tags' 'traces_en' 'serving_size'
 'no_nutriments' 'additives_n' 'additives' 'additives_tags' 'additives_en'
 'ingredients_from_palm_oil_n' 'ingredients_from_palm_oil'
 'ingredients_from_palm_oil_tags'
 'ingredients_that_may_be_from_palm_oil_n'
 'ingredients_that_may_be_from_palm_oil'
 'ingredients_that_may_be_from_palm_oil_tags' 'nutrition_grade_uk'
 'nutrition_grade_fr' 'pnns_groups_1' 'pnns_groups_2' 'states'
 'states_tags' 

Какое название у 105 столбца?

In [216]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [217]:
food.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [218]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [219]:
food.iloc[18].loc['product_name']

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [2]:
import pandas as pd
import requests
import io

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

r = requests.get(url)
if r.ok:
    data = r.content.decode('utf8')
    chipo = pd.read_csv(io.StringIO(data), delimiter='\t',encoding='utf-8', low_memory=False)
    
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [4]:
chipo['item_price_float'] = chipo['item_price'].map(lambda price: float(price[1:])) # создаем столбец, в котором цена - в виде float
filtered = chipo[chipo['item_price_float'] > 10.00]
len(filtered.index)

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [15]:
print(chipo.loc[:,['item_name','item_price']])

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17        

Отсортировать по имени предмета

In [21]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  \
3389                                        [Diet Coke]    $12.98    
341                                         [Diet Coke]     $6.49    
1849                                             [Coke]     $6.49    
1860                                        [Diet Coke]     $6.49    
2713                                             [Coke]     $6.49    
3422                                             [Coke]     $6.49    
553                                         [Diet Coke]     $6.49    
1916                                        [Diet Coke]     $6.49    
1922                                             [Coke]     $6.49    
1937                                        [Diet Coke]     $6.49    
3836                                             [Coke]     $6.49    
298                                            [Sprite]     $6.49    
1976                                        [Diet Coke]     $6.49    
1167                                             [Coke]     $6.49    
3875                                     

Сколько было заказано самого дорогого предмета?

In [58]:
# трактовака условия 1:
#   в данных нет идентификатора предмета,
#   то есть, с одним названием - могут встречаться разные предметы.
#   Например, название совпадает, но цена разная - это разные предметы
# решение 1:
#   отсортировать по цене, взять первый.
#   Взять значение из столбца quantity
#   Ограничение: считаем, что только 1 запись с максимальной ценой
chipo_sorted = chipo.sort_values(by=['item_price_float'], ascending=False)
chipo_sorted.head()
top_price = chipo_sorted.iloc[0,5]
row_of_interest = chipo_sorted[chipo_sorted['item_price_float'] == top_price]
assert len(row_of_interest) == 1
row_of_interest.iloc[0, 1]


15

In [53]:
# трактовка условия 2: 
#   считаем, что идентификатор предмета - его название,
#   и в других заказах этот предмет может быть с другой ценой.
# решение:
#   отсортировать по цене, взять первый, его название.
#   Теперь из всего набора выбрать записи, в которых такой предмет.
#   Просуммировать quantity.
chipo_sorted = chipo.sort_values(by=['item_price_float'], ascending=False)
top_item = chipo.sort_values(by=['item_price_float'], ascending=False).iloc[0,2] # если указать через loc - тогда не понятно как отметить первую строку, т.к. считает 0 как название
rows_of_interest = chipo[chipo['item_name']==top_item]
total_count = sum(rows_of_interest.loc[:,'quantity'])

total_count

130

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [64]:
rows_of_interest = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
# Решение 1: кол-во предметов, которые заказали в сумме
print(sum(rows_of_interest['quantity']))
# Решение 2: кол-во раз (строк), в которых заказывают этот предмет
len(rows_of_interest)

18


18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [73]:
rows_of_interest = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
len(rows_of_interest)

20